[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "threader"
author = "Chris Holdgraf"
author-email = "choldgraf@berkeley.edu"
home-page = "https://github.com/choldgraf/threader"
classifiers = ["License :: OSI Approved :: MIT License"]

